// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteMatchLog(arg1) {
  return window['go']['backend']['App']['DeleteMatchLog'](arg1);
}

export function DomReady(arg1) {
  return window['go']['backend']['App']['DomReady'](arg1);
}

export function GetAppVersion() {
  return window['go']['backend']['App']['GetAppVersion']();
}

export function GetAvailableLogs() {
  return window['go']['backend']['App']['GetAvailableLogs']();
}

export function GetMatchHistory() {
  return window['go']['backend']['App']['GetMatchHistory']();
}

export function GetMatchLog(arg1) {
  return window['go']['backend']['App']['GetMatchLog'](arg1);
}

export function Initialize(arg1, arg2, arg3) {
  return window['go']['backend']['App']['Initialize'](arg1, arg2, arg3);
}

export function IsInitialized() {
  return window['go']['backend']['App']['IsInitialized']();
}

export function IsTracking() {
  return window['go']['backend']['App']['IsTracking']();
}

export function OpenResultsDirectory() {
  return window['go']['backend']['App']['OpenResultsDirectory']();
}

export function RefreshData(arg1, arg2) {
  return window['go']['backend']['App']['RefreshData'](arg1, arg2);
}

export function StartTracking(arg1, arg2) {
  return window['go']['backend']['App']['StartTracking'](arg1, arg2);
}

export function StopTracking() {
  return window['go']['backend']['App']['StopTracking']();
}

export function Track(arg1, arg2) {
  return window['go']['backend']['App']['Track'](arg1, arg2);
}
