// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteMatchLog(arg1) {
  return window['go']['core']['App']['DeleteMatchLog'](arg1);
}

export function DomReady(arg1) {
  return window['go']['core']['App']['DomReady'](arg1);
}

export function ExportLogToCSV(arg1) {
  return window['go']['core']['App']['ExportLogToCSV'](arg1);
}

export function FetchData(arg1, arg2, arg3) {
  return window['go']['core']['App']['FetchData'](arg1, arg2, arg3);
}

export function GetAppVersion() {
  return window['go']['core']['App']['GetAppVersion']();
}

export function GetAvailableLogs() {
  return window['go']['core']['App']['GetAvailableLogs']();
}

export function GetMatchHistory() {
  return window['go']['core']['App']['GetMatchHistory']();
}

export function GetMatchLog(arg1) {
  return window['go']['core']['App']['GetMatchLog'](arg1);
}

export function Initialize(arg1, arg2, arg3) {
  return window['go']['core']['App']['Initialize'](arg1, arg2, arg3);
}

export function IsInitialized() {
  return window['go']['core']['App']['IsInitialized']();
}

export function IsTracking() {
  return window['go']['core']['App']['IsTracking']();
}

export function OpenResultsDirectory() {
  return window['go']['core']['App']['OpenResultsDirectory']();
}

export function ResultsJSONExist() {
  return window['go']['core']['App']['ResultsJSONExist']();
}

export function StartTracking(arg1, arg2) {
  return window['go']['core']['App']['StartTracking'](arg1, arg2);
}

export function StopTracking() {
  return window['go']['core']['App']['StopTracking']();
}
