// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetSF6BattleStatsComparison(arg1:string):Promise<model.SF6BattleStatsComparisonReport>;
