// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {cmd} from '../models';
import {tracker} from '../models';

export function ForcePoll():Promise<void>;

export function SelectGame(arg1:model.GameType):Promise<void>;

export function SetEventEmitter(arg1:cmd.EventEmitFn):Promise<void>;

export function SetGameTracker(arg1:tracker.GameTracker):Promise<void>;

export function StartTracking(arg1:string,arg2:boolean):Promise<void>;

export function StopTracking():Promise<void>;
