// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsTracking():Promise<boolean>;

export function StopTracking():Promise<void>;

export function Track(arg1:string):Promise<boolean>;
