// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsTracking():Promise<boolean>;

export function SetCFN(arg1:string):Promise<string>;

export function StopTracking():Promise<void>;
