// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteMatchLog(arg1) {
  return window['go']['main']['App']['DeleteMatchLog'](arg1);
}

export function GetAvailableLogs() {
  return window['go']['main']['App']['GetAvailableLogs']();
}

export function GetMatchHistory() {
  return window['go']['main']['App']['GetMatchHistory']();
}

export function GetMatchLog(arg1) {
  return window['go']['main']['App']['GetMatchLog'](arg1);
}

export function IsInitialized() {
  return window['go']['main']['App']['IsInitialized']();
}

export function IsTracking() {
  return window['go']['main']['App']['IsTracking']();
}

export function OpenResultsDirectory() {
  return window['go']['main']['App']['OpenResultsDirectory']();
}

export function StopTracking() {
  return window['go']['main']['App']['StopTracking']();
}

export function Track(arg1) {
  return window['go']['main']['App']['Track'](arg1);
}
