// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteMatchLog(arg1:string):Promise<void>;

export function GetAvailableLogs():Promise<Array<string>>;

export function GetMatchHistory():Promise<main.MatchHistory>;

export function GetMatchLog(arg1:string):Promise<Array<main.MatchHistory>>;

export function IsInitialized():Promise<boolean>;

export function IsTracking():Promise<boolean>;

export function OpenResultsDirectory():Promise<void>;

export function StopTracking():Promise<void>;

export function Track(arg1:string):Promise<boolean>;
