// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {errorsx} from '../models';
import {model} from '../models';
import {locales} from '../models';
import {context} from '../models';

export function CheckForUpdate():Promise<boolean>;

export function GetAppVersion():Promise<string>;

export function GetFormattedErrorModelUnused():Promise<errorsx.FormattedError>;

export function GetGuiConfig():Promise<model.GuiConfig>;

export function GetMatches(arg1:number,arg2:string,arg3:number,arg4:number):Promise<Array<model.Match>>;

export function GetSessions(arg1:string):Promise<Array<model.Session>>;

export function GetSupportedLanguages():Promise<Array<string>>;

export function GetThemes():Promise<Array<model.Theme>>;

export function GetTranslation(arg1:string):Promise<locales.Localization>;

export function GetUsers():Promise<Array<model.User>>;

export function OpenResultsDirectory():Promise<void>;

export function SaveLocale(arg1:string):Promise<void>;

export function SaveSidebarMinimized(arg1:boolean):Promise<void>;

export function SaveTheme(arg1:model.ThemeName):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
