// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ForcePoll():Promise<void>;

export function SelectGame(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartTracking(arg1:string,arg2:boolean):Promise<void>;

export function StopTracking():Promise<void>;
