name: Run go tests
on:
  pull_request:
    paths:
      - "**.go"

jobs:
  go-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'app/go.mod'
          cache-dependency-path: 'app/go.sum'

      - run: go test ./... -v -count=1 -p 4 -race
